# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 17, Introduction To Mathematics
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-01-30 Fri>
#+DESCRIPTION: Seventh asssignment in the course Introduction To Mathematics
#+KEYWORDS: Introduction To Mathematics, Assignment, Set Theory
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage[backend=bibtex, style=numeric]{biblatex}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \addbibresource{bibliography.bib}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -bibtex -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

\clearpage

* Problems

** Problem 1
   1. Let $A$ and $B$ be points, and let $\ell$ be a line crossing the segment
      $AB$ in the point $C$.  Prove that from four axioms of incidence and the
      Pasch's axiom it follows that there are two distinct points on $\ell$.
   2. Prove from four axioms of incidence and the axioms of order it follows
      that there doesn't exist a line which contains just one point.

*** Answer 1
    Sorry, I don't know what definitions do you have in mind, but every
    definition of incidence geometry that I could find, for example this one:
    https://www.imsc.res.in/~kapil/geometry/euclid/node2.html flat out says
    /Every line contains at least two distinct points./ This means that the
    proof is extremely trivial, it is simply the reiteration of the first
    axiom.

    Anoter reference: [[http://www.uwyo.edu/moorhouse/handouts/incidence_geometry.pdf][Moorhouse, G. Eric. "Incidence Geometry"]] (page 5):

    /The preceding paragraph talks about partial linear space:/
    
    #+BEGIN_QUOTE
    (PLS1) Any two distinct points lie on at most one common line.
    (PLS2) Every line has at least two points.
    #+END_QUOTE

    /And even stricter for linear space:/
    #+BEGIN_QUOTE
    (LS1) Any two distinct points lie on exactly one common line.
    (LS2) Every line has at least two points.
    #+END_QUOTE

*** Answer 2
    Exactly by the same reasoning as [[Answer 1]] the proof is trivially the
    reiteration of the first axiom.  I will also note that whether we use
    order axioms or just Pasch's axiom is inconsequential for the proof.

** Problem 2
   1. Prove using the four axioms of incidence and the axiom of parallels 
      that there exist at least six lines.
   2. Does it follow from the same system as mentioned in (1) that there
      exist seven lines?

*** Answer 3
    In order to prevent confusion I will list the axioms in the way that
    I'm familiar with:

    1. There are at least two distinct points.
    2. There is one and only one line that contains two distinct points.
    3. Every line contains at least two distinct points.
    4. There are three points that do not all lie on the same line.
    5. For any three points that do not lie on the same line there is 
       a one and only one plane that contains them.
    6. Any plane contains at least three points. 
    7. If a line lies on a plane then every point contained in the line 
       lies on that plane.
    8. If a line contains two points which lie on a plane then the line 
       lies on the plane.
    9. If two planes both contain a point then they also contain a line.
    10. There are at least four points that do not all lie on the same plane.
        
    The axiom of parallels:

    + Given a line and a point outside it there is exactly one line through the
      given point which lies in the plane of the given line and point so that
      the two lines do not meet.
    
    Without giving a proof, I will note that the smallest model for this
    system has 12 planes and 36 lines, so this is probably a wrong system.

    Another system of incidence axioms with parallelism I could find was
    in Shafarevich's Basic Notions of Algebras:

    1. Through any two distinct points there is one and only one line.
    2. Given any line and a point not on it, there exists one and only one
       other line through the point and not intersecting the line (that is,
       parallel to it).
    3. There exist three points not on any line.
       
    The minimal (in terms of objects used) model for this system may be
    a ``tick-tack-toe'' with two extra ``diagonal'' lines crossing it, in
    other words, it is the points $A, B, C, D$ and lines $AB$, $BC$, $CD$,
    $DA$, $AC$ and $BD$.  The following is an attempt to prove that such
    system is minimal.

    From (3) follows there are at least 3 points, let's name them $A$,
    $B$ and $C$.  By (1) this gives us that there must be these lines:
    $AB$, $BC$ and $CA$.  In order to satisfy (2) we need add one more point.
    This is so because we know that $A$, $B$ and $C$ are not on the same
    line.  Observe now that any of the three points is not on the same
    line with any two remaing points.  But, by adding point $D$ we are
    able to satisfy the requirement of (2) by adding three more lines:
    $CD$, $DA$ and $BD$.  Now all requirements are satisfied and we have
    exactly six lines in the model.  Hence, there must be at least six
    lines.

*** Answer 4
    As can be seen from the [[Answer 3]], there is no requirement that there
    be seven lines in the system (I just demonstrated a model with
    exactly six lines).

** Problem 3
   Prove or disprove:
   1. If $n$ is a natural number, then if $6|n^2$ $6|n$.
   2. If $n$ is a natural number, then if $12|n^2$ $12|n$.
   3. Let $A*$ be a set generated by multiplication from 
      $\{24, \frac{1}{8}, \frac{1}{3}\}$ then ${288 \in A*}$.
   4. There exist natural numbers $x,y,z,t$ such that \\
      ${28^x \times 21^{y-1} -16^z \times 49^t = 0}$.

*** Answer 5
    Yes, this follows from uniqueness of prime factorization.  Any square
    of a real number will have to contain at least twice every one of the
    prime factors of $n$.  This, in turn, implies that if $n^2$ is divisible
    by 6, then it has to have both 3 and 2 twice in its prime factorization,
    therefore $\sqrt{n^2}$ will contain both 2 and 3, therefore it will be
    divisible by 6.

*** Answer 6
    This is not necessarily so since if $n^2$ is divisible by 12, it needs
    not have the prime factor 2 repeated four times (two would be still enough).
    So, for example $n=6$, $6\times6=36$, 36 is divisible by 12, but 6 isn't.

*** Answer 7
    No, this isn't possible because of the prime factorization of 288 containing
    five twos, but it is not possible to produce this many twos from prime
    factorizations of 24 and 8.  In other words any multiple of 8 and 24 will
    have a number of twos divisible by three, and 3 (the remaining member of
    the generating set) has no influence on the number of twos in the generated
    set members.

*** Answer 8
    Yes, this is possible.  If we look at the prime factorization of the
    left product, it has $\{2, 7, 3\}$, and the product on the right has
    prime factorization containing $\{2, 7\}$.  But we can eliminate the
    factor 3 from the first factorization by setting $y=1$, thus removing
    it from equation.  And, indeed, assignment $x=2, y=1, z=1, t=1$ solves
    this equation.

** Problem 4
   1. Given a sequence defined as follows:
      $a_1=1$, and for all $n$ being natural numbers,
      $a_{n+1}=a_n+\frac{1}{n(n+1)}$.  Prove by induction that for all $n$
      being natural numbers $a_n = 2 - \frac{1}{n}$.
   2. Prove using induction that for all $n$ being natural numbers it holds
      that $13|10^{2n-1}+3^{2n-1}$.

*** Answer 9
    The conjecture is false, already for the value of $n=2$ both formulae give
    different values:
    
    $a_n+\frac{1}{n(n+1)}=1+\frac{1}{2(2+1)}=\frac{7}{6}$

    while:

    $2 - \frac{1}{n}=2 - \frac{1}{2}= \frac{3}{2}$.

*** Answer 10
    I will prove, using mathematical induction on $n \in \mathbb{N}$ that 13
    divides any sum of odd powers of 10 and 3.  First, the intuition for the
    proof: what we need to convince ourselves in is that the number added at any
    recursion step must be divisible by 13.  This is so since if $x$ is
    divisible by $y$, then if $x+z$ is divisible by $y$, then it follows that
    $z$ is, too, divisible by $y$.  The most work of this proof is centered
    around finding $z$.

    *Base step* is trivially true: $10+3=13$, $13|13$.

    *Induction step.* I will reformulate the original statement equivalently
    as $10^{2n-1}+3^{2n-1}=13x$ where $x \in \mathbb{N}$.  This will
    simplify the naming.

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        10^{2n-1}+3^{2n-1} &= 13x \\
        10^{2(n+1)-1}+3^{2(n+1)-1} &= 13x + 10^{2n-1}+3^{2n-1} \\
        & \textrm{by induction hypothesis} \\
        10^{2n+1}+3^{2n+1} &= 13x + 10^{2n-1}+3^{2n-1} \\
        & \textrm{by simple calculus} \\
        10^{2n+1}+3^{2n+1}-10^{2n-1}-3^{2n-1} &= 13x \\
        & \textrm{collecting summands on one side} \\
        10^{2n-1}(10^2)-10^{2n-1}+3^{2n-1}(3^2)-3^{2n-1} &= 13x \\
        & \textrm{by $x^{y+z}=x^yx^z$} \\
        10^{2n-1}(99)+3^{2n-1}(8) &= 13x \\
        & \textrm{by simple calculus} \\
        10^{2n-1}(91) &= 13x' \\
        & \textrm{$13|10^{2n-1}(8)+3^{2n-1}(8)$} \\
        & \textrm{by induction hypothesis} \\
        10^{2n-1}(13*7) &= 13x' \\
        & \textrm{$x' \in \mathbb{N}$} \\
      \end{align*}
    #+END_SRC

    In other words, I've showed that the number added at each recursive step must
    be divisible by 13, hence, by mathematical induction, $13|10^{2n-1}+3^{2n-1}$.
