# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 14, Introduction To Mathematics
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2014-12-19 Fri>
#+DESCRIPTION: Second asssignment in the course Introduction To Mathematics
#+KEYWORDS: Introduction To Mathematics, Assignment, Set Theory
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage[backend=bibtex, style=numeric]{biblatex}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \addbibresource{bibliography.bib}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -bibtex -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

\clearpage

* Problems

** Problem 1

   Given $A = \{1, 2\}$ and $B = \mathbb{N}$.
   1. Describe all functions from $A$ to $B$, which are not one-to-one (bijective).
   2. Describe all functions from $B$ to $A$ which are not onto.
   3. Prove or disprove:
      + There exist functions $f : A \to B$ and $g : B \to A$ such that $f \circ g$
        has an inverse.
      + There exist functions $f : A \to B$ and $g : B \to A$ such that $g \circ f$
        has an inverse.

*** Answer 1

    Let's first give a name for any function $f : A \to B$.  Now, any $f$, which sends
    either of the elements of $A$ (of which there are two) to the same element of
    $B$ would be non-bijective.  We can describe the set of all such functions using
    this formula:

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        F = \{(a,b) |
        a \in A,
        b \in B,
        \exists a' \in A: a' \neq a \land f(a) = f(a') \}
      \end{equation*}
    #+END_SRC

    To make this more concrete: all functions $f$ which assign the same value in $B$ to
    either 1 or 2 are non-bijections.  This is assuming $f$ is defined for all inputs.

*** Answer 2

    Let's, again, give a name for all functions from $B$ to $A$, viz. $g : B \to A$.
    The function is onto (surjective) iff every value in its codomain has an origin
    in its domain.  We can describe all such functions using this formula:

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        G = \{(b,a) |
        a \in A,
        b \in B,
        \forall b' \in B: g(b) = g(b') \}
      \end{equation*}
    #+END_SRC

    Or, in other words, all functions which send all elements of $B$ to the same
    element of $A$ (be it 1 or 2), are not surjective.

*** Answer 3
    Yes, there exist such functions.  For example, $g$ may be defined to return
    1 if the input is odd and 2, when the input is even.  Then, if $f$ sends
    its input to an odd number, given 1 and to an even number, given 2, the
    composition $f \circ g$ is simply the identity function.

*** Answer 4
    We, however, cannot define a $g \circ f$ function with an inverse.  The
    intuition behind this is that we lose information by sending elments from a
    larger domain to a smaller one.  More formally, we can procede by pigeonhole
    principle, seeing how any function $g$ (provided it is defined for all
    inputs) would have to send its input to the same element in $A$, while
    afterwards there would be no way of distinguishing that element from the one
    obtained by earlier applicatin of $g$.

** Problem 2
   Given $f : A \to B$ and $C \subseteq A$.
   
   1. Prove that $C \subseteq f^{-1}(f(C))$.
   2. Prove that if $f$ is a bijection, then $C = f^{-1}(f(C))$.
   3. Show sets $A$, $B$, $C$ and function $f:A \to B$ such that it holds that
      $C \subset f^{-1}(f(C))$.

*** Answer 5
    Let's assume by contradiction, that there exists $d$ in $D = A \setminus C$,
    such that it is in the codomain of $f^{-1}$.  Existence of sucn an element
    would in turn imply existence of element $b \in B$ such that $f^{-1}(b) = d$.
    This would in turn imply existence of $c \in C$ such that $f(c) = b$.
    But by the definition of inverse, $f^{-1}(b)=c$ and $c \in C$, while we
    assumed the contrary.  Since our initial assumption failed, it must be the
    case that the elements of codomain of $f^{-1}$ must come from $C$.

*** Answer 6
    Since $f$ is a bijection, it's inverse must be a bijection too (otherwise it
    would not be able to assign to all the elements in its image all the values in
    its domain).  Composition of two bijections is necessarily a bijection, thus
    $C = f^{-1}(f(C))$.

*** Answer 7
    Below is a minimal example of the inverse function being partial to $f$:
    
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        A &= \{1, 2, 3\} \\
        B &= \{1, 2, 3\} \\
        C &= \{1, 2\} \\
        f(1) &= 1 \\
        f(2) &= 1 \\
        f^{-1}(1) &= 1
      \end{align*}
    #+END_SRC

** Problem 3
   Given functions $f$ and $g$ both are from $\mathbb{N}$ to $\mathbb{N}$.
   $g$ is known to be onto and for all $n$ in $\mathbb{N}$ it holds that

   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{equation*}
       (f \circ g)(n) = 2n - 1
     \end{equation*}
   #+END_SRC

   1. Prove that $f$ is not surjective.
   2. Prove that $f$ is bijective.
   3. Show such $f$ and $g$ that satisfy the formula given above.

*** Answer 8
    Suppose, by contradiction, that $f$ was surjective, this would imply
    that any even number, in particular, the number 2 in the image of $f$
    would have to have its origin in $\mathbb{N}$, but the origin of 2 is in
    $\mathbb{Q}$, but not in $\mathbb{N}$, i.e.
    $n = \frac{1}{2} \implies 2n - 1 = 2$.  Because we know that $g$ is
    surjective, it must be $f$, which is not surjective (the composition
    of surjective functions is surjective).

*** Answer 9
    Suppose $f$ is not bijective, this woul3d imply there exist
    $x, x' \in \mathbb{N}$ such that $x \neq x'$ while $x = 2n - 1$
    and $x' = 2n - 1$, which is a contradiction.

*** Answer 10
    The simplest example would be to take $g$ equal to identity and $f$
    being $f(n) = 2n - 1$.  The argument for $f$ not being surjective is
    essentially the same as in [[Answer 8]].

** Problem 4
   Let $G$ be a group with $*$ being the group operation.  Let also $a \in G$.
   Given a function $f : G \to G$ defined as
   $\forall x \in G: f(x) = a^{-1} * x * a$.

   1. Prove that $f$ is surjective and bijective.
   2. Find $f^{-1}$.
   3. Prove that if $b, c \in G$ are each others inverses, then the same is
      true of $f(b)$ and $f(c)$.

*** Answer 11
    Suppose $f$ was not bijective, this would imply that there could be
    $a^{-1} * x * a = a^{-1} * x' * a$ for some $x \neq x'$.  But using group
    cancellation property we could reduce $a^{-1} * x * a = a^{-1} * x' * a$ to
    $x = x'$, obtaining contradiction.  Hence $f$ is a bijection.

    $x$ is defined to be a member of $G$.  Since $G$ is closed under $*$, it
    means that there can't be any values in the domain of $f$ which are not in
    its co-domain.  In other words, suppose there was a $x' \in G$, which cannot
    be produced by $f(x)$, that is, if we look at the operation table, each
    column of this table will have to have as many rows as there are elements.
    But no two rows in this column can repeat because this would defy the
    cancellation property (i.e. it would mean that for some $p, q, r, s$ it
    would be that $p * q = r$ and $p * s = r$, $r$ being the value, which repeats
    in the selected column and $q, s$ are the elements for which it repeats.
    Hence $f$ must be onto (surjective).

*** Answer 12
    By definition of inverse, applying the group operation to inverse and the
    element it is inverse of will give us the identity element:

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        (a^{-1} * x * a) * (a^{-1} * x * a)^{-1} & = a^{-1} * a
        & \textrm{given} \\
        x * a * (a^{-1} * x * a)^{-1} & = a
        & \textrm{by group cancellation property} \\
        x^{-1} * x * a * (a^{-1} * x * a)^{-1} & = x^{-1} * a
        & \textrm{again, by group cancellation property} \\
        a * (a^{-1} * x * a)^{-1} & = x^{-1} * a
        & \textrm{by group operation on inverses} \\
        a^{-1} * a * (a^{-1} * x * a)^{-1} & = a^{-1} * x^{-1} * a
        & \textrm{by cancellation property} \\
        (a^{-1} * x * a)^{-1} & = a^{-1} * x^{-1} * a
        & \textrm{by group operation on inverses}
      \end{align*}
    #+END_SRC

    Hence $f^{-1}(x) = a^{-1} * x^{-1} * a$.

*** Answer 13
    Provided $b = c^{-1}, c = b^{-1}$, the next equalities hold:

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{array}{lllllll}
          f(b) & = & a^{-1} * b * a & = & a^{-1} * c^{-1} * a & = & f(c^{-1}) \\
          f(c) & = & a^{-1} * c * a & = & a^{-1} * b^{-1} * a & = & f(b^{-1}) \\
        \end{array}
      \end{equation*}
    #+END_SRC

    Which is what we were asked to prove.
